### ISSUE TITLE
Syntax error in the (Advanced) Syntax Question under the Define IIFE section

### ISSUE THREAD

**Issue by harumhelmy** [learn-co-curriculum/js-advanced-functions-basic-functions-review-lab#7]
`(function(x){ return x + 2 }()2)` 

should be

`(function(x){ return x + 2 })(2)`

The irony! :)

**Comment by maxwellbenton** [comment]
Hi @harumhelmy,

This typo has been fixed! Thank you for spotting this and providing feedback!
