### ISSUE TITLE
Confusing example

### ISSUE THREAD

**Issue by Case757** [learn-co-curriculum/js-advanced-functions-basic-functions-review-lab#9]
The example listed below was a bit confusing. I assumed the arithmetic was related to the function above because the numbers were similar. More clarification or a different example would be helpful. Thank you!
____________________________________________
Define an IIFE: Instantly-Invoked Function Expression
As a thought experiment, what happens here:

(function(x){ return x + 3 })(2) //=> ???
We recognize the first () as being those that we might use from arithmetic:

( 3 - 4 ) * 2 // => -2

**Comment by sgharms** [comment]
Seems reasonable. Updated
